variable "tenancy_ocid" {}
variable "compartment_ocid" {}
variable "ssh_private_key" {}
variable "public-ip" {}
variable "instance_user" {}
variable "docker_user" {}
variable "docker_password" {}
variable "user_ocid" {}
variable "fingerprint" {}
variable "key_file" {}
variable "tenancy" {}
variable "region" {}
